# Generated by Django 5.0.1 on 2024-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_delete_exit_asset_location_asset_time_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='facial_data',
            field=models.ImageField(blank=True, null=True, upload_to='facial_data/', verbose_name='Facial Data'),
        ),
    ]
