# Generated by Django 5.0.1 on 2024-05-13 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userenrolled_facial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='footage',
            field=models.ImageField(blank=True, null=True, upload_to='assets_footage/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userenrolled',
            name='orientation',
            field=models.FileField(upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])]),
        ),
    ]
