# Generated by Django 5.0.1 on 2024-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_asset_footage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag_id',
            field=models.IntegerField(unique=True),
        ),
    ]
