# Generated by Django 5.0.1 on 2024-05-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_asset_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenrolled',
            name='facial_data',
        ),
        migrations.CreateModel(
            name='FacialDataImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facial_data_images/')),
                ('user_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_data_images', to='app1.userenrolled')),
            ],
        ),
        migrations.AddField(
            model_name='userenrolled',
            name='facial_data',
            field=models.ManyToManyField(blank=True, related_name='users_with_facial_data', to='app1.facialdataimage'),
        ),
    ]
