# Generated by Django 5.0.1 on 2024-05-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_userenrolled_facial_data_facialdataimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenrolled',
            name='facial_data',
        ),
    ]
