# Generated by Django 5.0.1 on 2024-05-13 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_userenrolled_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='orientation',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='userenrolled',
            name='tag_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
